version: '3'

services:
  video-streaming:
    image: video-streaming-fluxtube
    build:
      context: ./video-streaming
      dockerfile: dockerfile-prod
    container_name: video-streaming-fluxtube
    volumes:
      # This volume is primarily for speeding up image builds if frequent rebuilds are conducted locally.
      - /tmp/video-streaming/npm-cache:/home/node/.npm:z
    ports:
      # Map the host port 4001 to container port 3000
      - "4001:3000"
    environment:
      # Set the internal port the Node.js application listens on.
      - PORT=3000
      - NODE_ENV=production
    restart: "no"

  video-storage-local:
    image: video-storage-local-fluxtube
    build:
      context: ./video-storage-local
      dockerfile: dockerfile-prod
    container_name: video-storage-local-fluxtube
    volumes:
      - /tmp/video-storage-local/npm-cache:/home/node/.npm:z
      - ./video-storage-local/storage:/usr/src/app/storage:z
    ports:
      - "4005:3000"
    environment:
      - PORT=3000
    restart: "no"